# SPDX-License-Identifier: Apache-2.0
---
# group_vars tasks file for docker_compose role_generator

- name: Create group_vars file
  when:
    - gen_group_vars_enable | bool
    - (only_files is not defined) or ('group_vars') in only_files
  ansible.builtin.template:
    src: "group_vars/group_vars.yml.j2"
    dest: "{{ gen_rootdir_group_vars }}/{{ group }}/{{ gen_role_name }}.yml"
    mode: '0644'
  loop: "{{ gen_group_vars_groups }}"
  loop_control:
    label: "{{ group }}"
    loop_var: group
