# SPDX-License-Identifier: Apache-2.0
---
# main tasks file for docker_compose role_generator

- name: Ensure role name is valid
  ansible.builtin.set_fact:
    gen_role_name: "{{ gen_role_name | to_varname }}"

- name: Capture current working directory
  when: gen_dest_dir is not defined
  ansible.builtin.set_fact:
    gen_dest_dir: "{{ lookup('ansible.builtin.env', 'PWD') }}"

# Role directory — base structure, per-service files, then overlays
- name: Deploy role base skeleton template
  ansible.builtin.include_tasks:
    file: render_skeleton.yml
  vars:
    dest_path: "{{ gen_role_dir_path }}"
    skeleton_path: "templates/_role_base"

- name: Deploy role service skeleton template
  ansible.builtin.include_tasks:
    file: render_skeleton.yml
  loop: "{{ gen_role_services }}"
  loop_control:
    loop_var: service_item
    label: "{{ service_item }}"
  vars:
    dest_path: "{{ gen_role_dir_path }}"
    skeleton_path: "templates/_role_service"
    rename_regex: '__service__'
    rename_replacement: '{{ service_item }}'

- name: Deploy overlay skeleton templates
  ansible.builtin.include_tasks:
    file: render_skeleton.yml
  vars:
    dest_path: "{{ gen_role_dir_path }}"
    skeleton_path: "templates/overlay_{{ overlay_item }}/templates"
  loop: "{{ gen_role_overlays }}"
  loop_control:
    loop_var: overlay_item
    label: "{{ overlay_item }}"

# Separate artifacts
- name: Deploy SSH key pair
  when: gen_ssh_keypair_enable | bool
  ansible.builtin.include_tasks:
    file: ssh_keypair.yml

- name: Deploy playbook from skeleton template
  when: gen_playbook_enable | bool
  ansible.builtin.include_tasks:
    file: render_skeleton.yml
  vars:
    dest_path: "{{ gen_rootdir_playbooks }}"
    skeleton_path: "templates/playbook"
    rename_regex: '__playbook__.yml'
    rename_replacement: '{{ gen_playbook_name }}'

- name: Deploy group_vars from skeleton template
  when: gen_group_vars_enable | bool
  ansible.builtin.include_tasks:
    file: render_skeleton.yml
  vars:
    dest_path: "{{ gen_rootdir_group_vars }}/{{ group_item }}/"
    skeleton_path: "templates/group_vars"
    rename_regex: '__role__'
    rename_replacement: '{{ gen_role_name }}'
  loop: "{{ gen_group_vars_groups }}"
  loop_control:
    label: "{{ group_item }}"
    loop_var: group_item

- name: Deploy vaulted group_vars from skeleton template
  when: gen_vaulted_vars_enable | bool
  ansible.builtin.include_tasks:
    file: render_skeleton.yml
  vars:
    dest_path: "{{ gen_rootdir_group_vars }}/{{ group_item }}/"
    skeleton_path: "templates/group_vars_vaulted"
    rename_regex: '__role__'
    rename_replacement: '{{ gen_role_name }}'
    render_force: false
  loop: "{{ gen_vaulted_vars_groups }}"
  loop_control:
    label: "{{ group_item }}"
    loop_var: group_item
