# SPDX-License-Identifier: Apache-2.0
---
# playbook tasks file for docker_compose role_generator
- name: Create playbook directory
  ansible.builtin.file:
    path: "{{ gen_rootdir_playbooks }}"
    state: directory
    mode: '0755'

- name: Create playbook for role
  when:
    - gen_playbook_enable | bool
    - (only_files is not defined) or ('playbook') in only_files
  ansible.builtin.template:
    src: playbook/playbook.yml.j2
    dest: "{{ gen_rootdir_playbooks }}/{{ gen_playbook_name }}"
    mode: '0644'
