# SPDX-License-Identifier: Apache-2.0
---
# role tasks file for docker_compose role_generator

- name: Create role directory structure
  ansible.builtin.file:
    path: '{{ gen_role_dir_path }}'
    state: directory
    mode: '0755'

- name: Create parent directories for role files
  with_community.general.filetree: 'templates/role'
  when: skeleton_item.state == 'directory'
  ansible.builtin.file:
    path: '{{ (gen_role_dir_path, skeleton_item.path) | path_join }}'
    state: directory
    mode: '0755'
  loop_control:
    label: '{{ skeleton_item.path }}'
    loop_var: skeleton_item

# Blocks: <% %>
# Variables: << >>
- name: Render role files from skeleton
  with_community.general.filetree: 'templates/role'
  when:
    - skeleton_item.state == 'file'
    - skeleton_item.src | basename != '.git_keep'
    - (only_files is not defined) or (skeleton_item.path | regex_search(only_files))
  ansible.builtin.template:
    src: '{{ skeleton_item.src }}'
    # Your template files should be stored with a .j2 file extension,
    # but should not be deployed with it. splitext|first removes it.
    dest: '{{ (gen_role_dir_path, skeleton_item.path) | path_join | splitext | first }}'
    mode: '{{ skeleton_item.mode }}'
  loop_control:
    label: '{{ skeleton_item.path }}'
    loop_var: skeleton_item
