# SPDX-License-Identifier: Apache-2.0
---
# ssh_keypair tasks file for docker_compose role_generator

- name: Generate SSH Keypair for service
  when:
    - gen_ssh_keypair_enable | bool
    - "'sshkey' | regex_search(gen_file_filter)"
  community.crypto.openssh_keypair:
    path: "{{ gen_role_dir_path }}/files/{{ gen_ssh_keypair_name }}"
    type: "{{ gen_ssh_keypair_type }}"
    comment: "{{ gen_role_name }}@{{ gen_role_tld }}"
    passphrase: "{{ gen_ssh_keypair_passphrase | default(omit) }}"
  register: ssh_keypair
