# SPDX-License-Identifier: Apache-2.0
---
# group_vars tasks file for docker_compose role_generator

- name: Create vaulted var file
  when:
    - gen_vaulted_vars_enable | bool
    - (only_files is not defined) or ('vaulted_vars') in only_files
  ansible.builtin.copy:
    dest: "{{ gen_rootdir_group_vars }}/{{ item }}/{{ gen_role_name }}.vault.yml"
    content: |
      # SPDX-License-Identifier: Apache-2.0
      ---
      # {{ item }} vaulted vars file for {{ gen_role_name }}
    mode: '0644'
  loop: "{{ gen_vaulted_vars_groups }}"
